---
- name: install
  hosts: local
  vars_files:
    - vars/packages.yml
  tasks:
#  - set_fact:    
#      ansible_python_default_interpreter: "{{ ansible_python_interpreter }}"
#      ansible_python_interpreter:  "/usr/bin/python2"
  - name: install packages
    dnf: 
      name: "{{ packages }}"
      state: present
#  - set_fact:     
#      ansible_python_interpreter: "{{ ansible_python_default_interpreter }}"
